spring:
  application:
    name: message-processor
  datasource:
    url: jdbc:postgresql://db_postgres:5432/hotels_aggregator_db
    driver-class-name: org.postgresql.Driver
    username: ha_admin
    password: ha_admin_pass
    hikari:
      minimumIdle: 2
      maximumPoolSize: 4
    jpa:
      show-sql: true
      open-in-view: false
      properties:
        hibernate:
          format_sql: true
  flyway:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db_postgres:5432/hotels_aggregator_db
    user: ha_admin
    password: ha_admin_pass
    locations: classpath:docker/db/migration
    clean-disabled: false
    enabled: true
    baseline-on-migrate: true
  kafka:
    brokers:
      - broker-1:29091
      - broker-2:29092
    consumer-group: messageProcessorsGroup
    backoff-interval: 5S
    backoff-max-failure: 2
    topic-listener-threads: 3
    request-topic-suffix: request
    reply-topic-suffix: reply
#Включение режима 'async-mode' должно быть согласовано у производителя и всех потребителей
    async-mode:
      enable: true
      topic-prefix: aggregate
#Интеграция работает только с включенными сервисами в базе и локальных настройках
#Если локальные настройки интеграции не заданы, то по-умолчанию применяются активные сервисы из базы
#Локальные настройки имеют более высокий приоритет, чем в базе
integration:
  base:
    url: http://localhost:8080/
    read-timeout: 15s
    connect-timeout: 2s
    topic-prefix: baseProvider
#В асинхронном режиме сообщений действует ограничение: один топик = один потребитель = один сервис
# если включено несколько сервисов в асинхронном режиме, то работать будет первый из списка
# из-за чего производитель, настроенный на ожидание определенного количество ответов,
# может не получать результат по некоторым сервисам
  providers:
    nifNif:
      url: http://hotels8090:8090/api/v1/
      read-timeout: 20s
      connect-timeout: 5s
      topic-prefix: nifNif
      enable: true
    nafNaf:
      url: http://hotels8091:8091/api/v1/
      read-timeout: 20s
      connect-timeout: 5s
      topic-prefix: nafNaf
      enable: true
    nufNuf:
      url: http://hotels8092:8092/api/v1/
      read-timeout: 20s
      connect-timeout: 5s
      topic-prefix: nufNuf
      enable: false
#logging:
#  level:
#    org.hibernate.SQL: DEBUG
#    org.hibernate.orm.jdbc.bind: TRACE
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#    org.zalando.logbook.Logbook: TRACE
#    org.apache.kafka: INFO
#    ru.otus: DEBUG


